### ISSUE TITLE
Option to choose AppleTV device

### ISSUE THREAD

**Issue by TheBlackBush** [stigger/trakt-for-appletv#13]
Hi,

Is there an option to choose which AppleTV device to connect to (I have 2 devices)?

**Comment by stigger** [comment]
No, that's not possible at the moment. It should be quite easy to tweak `on_service_state_change` to accept only the desired name.

**Comment by TheBlackBush** [comment]
OK, maybe you can consider working with that library?
https://github.com/postlund/pyatv

**Comment by stigger** [comment]
Don't know about its current state, but when I was developing this, that library did not support ATV functionality that I needed, and I don't see any reasons to replace my implementation with another. Switching to this (or any other) library would require much more work, than what is needed to allow selecting a specific device.

**Comment by wolverine30008** [comment]
Hi,
I have setup this script on a different Mac and we are receiving this error.
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
Any help or advice is appreciated.  Thanks
    On Saturday, May 16, 2020, 04:33:37 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 


Don't know about its current state, but when I was developing this, that library did not support ATV functionality that I needed, and I don't see any reasons to replace my implementation with another. Switching to this (or any other) library would require much more work, than what is needed to allow selecting a specific device.

**Comment by stigger** [comment]
What's the macOS version? What's the full stacktrace of the error?

**Comment by wolverine30008** [comment]
Catalina 10.15.4
Entered the python3 command and received this error:
```
Todds-MacBook-Pro:trakt-for-appletv-master toddrock$ python3 ./tvscrobbler.py 

./tvscrobbler.py:21: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  config = yaml.load(open('data/config.yml', 'r'))

Navigate to https://trakt.tv/oauth/authorize?client_id=dc705f550f50706bdd7bd55db120235cc68899dbbfb4fbc171384c1c1d30d7d4&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code

Authorization code: ADB10EC0

Enter code displayed by Apple TV: 8914

ready!

Exception in thread Thread-1:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open

    encode_chunked=req.has_header('Transfer-encoding'))

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output

    self.send(msg)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send

    self.connect()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect

    server_hostname=server_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket

    session=session

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create

    self.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)




During handling of the above exception, another exception occurred:




Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 184, in handle_netflix

    title = self.get_netflix_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 195, in get_netflix_title

    data = urlopen('https://www.netflix.com/title/' + contentIdentifier).read()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen

    return opener.open(url, data, timeout)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open

    response = self._open(req, data)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open

    '_open', req)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain

    result = func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open

    context=self._context, check_hostname=self._check_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open

    raise URLError(err)

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>




Exception in thread Thread-2:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open

    encode_chunked=req.has_header('Transfer-encoding'))

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output

    self.send(msg)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send

    self.connect()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect

    server_hostname=server_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket

    session=session

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create

    self.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)




During handling of the above exception, another exception occurred:




Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 184, in handle_netflix

    title = self.get_netflix_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 195, in get_netflix_title

    data = urlopen('https://www.netflix.com/title/' + contentIdentifier).read()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen

    return opener.open(url, data, timeout)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open

    response = self._open(req, data)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open

    '_open', req)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain

    result = func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open

    context=self._context, check_hostname=self._check_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open

    raise URLError(err)

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>




Exception in thread Thread-3:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open

    encode_chunked=req.has_header('Transfer-encoding'))

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output

    self.send(msg)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send

    self.connect()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect

    server_hostname=server_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket

    session=session

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create

    self.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)




During handling of the above exception, another exception occurred:




Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 184, in handle_netflix

    title = self.get_netflix_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 195, in get_netflix_title

    data = urlopen('https://www.netflix.com/title/' + contentIdentifier).read()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen

    return opener.open(url, data, timeout)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open

    response = self._open(req, data)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open

    '_open', req)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain

    result = func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open

    context=self._context, check_hostname=self._check_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open

    raise URLError(err)

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>




Exception in thread Thread-4:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open

    encode_chunked=req.has_header('Transfer-encoding'))

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output

    self.send(msg)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send

    self.connect()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect

    server_hostname=server_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket

    session=session

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create

    self.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)




During handling of the above exception, another exception occurred:




Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 184, in handle_netflix

    title = self.get_netflix_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 195, in get_netflix_title

    data = urlopen('https://www.netflix.com/title/' + contentIdentifier).read()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen

    return opener.open(url, data, timeout)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open

    response = self._open(req, data)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open

    '_open', req)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain

    result = func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open

    context=self._context, check_hostname=self._check_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open

    raise URLError(err)

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>




Exception in thread Thread-5:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 132, in handle_tv_app

    self.handle_tvshows(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 139, in handle_tvshows

    season_number, episode_number = self.get_itunes_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 165, in get_itunes_title

    known = self.config['itunes']['titles'].get(contentIdentifier)

KeyError: 'itunes'




Exception in thread Thread-6:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 132, in handle_tv_app

    self.handle_tvshows(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 139, in handle_tvshows

    season_number, episode_number = self.get_itunes_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 165, in get_itunes_title

    known = self.config['itunes']['titles'].get(contentIdentifier)

KeyError: 'itunes'




Exception in thread Thread-7:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 132, in handle_tv_app

    self.handle_tvshows(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 139, in handle_tvshows

    season_number, episode_number = self.get_itunes_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 165, in get_itunes_title

    known = self.config['itunes']['titles'].get(contentIdentifier)

KeyError: 'itunes'




Exception in thread Thread-8:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 132, in handle_tv_app

    self.handle_tvshows(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 139, in handle_tvshows

    season_number, episode_number = self.get_itunes_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 165, in get_itunes_title

    known = self.config['itunes']['titles'].get(contentIdentifier)

KeyError: 'itunes'




Exception in thread Thread-9:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 94, in <lambda>

    Thread(target=lambda: inner()).start()

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 91, in inner

    handler(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 132, in handle_tv_app

    self.handle_tvshows(operation, progress)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 139, in handle_tvshows

    season_number, episode_number = self.get_itunes_title(self.now_playing_metadata.contentIdentifier)

  File "/Users/toddrock/Desktop/trakt-for-appletv-master/scrobbling.py", line 165, in get_itunes_title

    known = self.config['itunes']['titles'].get(contentIdentifier)

KeyError: 'itunes'

```


    On Wednesday, May 20, 2020, 10:10:42 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 


What's the macOS version? What's the full stacktrace of the error?

**Comment by stigger** [comment]
Are the date/time settings correct on that mac?

**Comment by wolverine30008** [comment]
Yes. I have confirmed the date and time are correct.
    On Wednesday, May 20, 2020, 10:52:57 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 


Are the date/time settings correct on that mac?

**Comment by wolverine30008** [comment]
It looks like a load error is happening. Default loader is unsafe and then it points me to a web address for full details.
python3 ./tvscrobbler.py 
./tvscrobbler.py:21: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  config = yaml.load(open('data/config.yml', 'r'))

ready!

    On Thursday, May 21, 2020, 05:33:54 PM EDT, Todd Rock <wolverine30008@yahoo.com> wrote:  
 
  Yes. I have confirmed the date and time are correct.
    On Wednesday, May 20, 2020, 10:52:57 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 


Are the date/time settings correct on that mac?

**Comment by wolverine30008** [comment]
Do you have any suggestions - are you able to solve this issue?


Sent from Yahoo Mail for iPad


On Thursday, May 21, 2020, 5:52 PM, Todd Rock <wolverine30008@yahoo.com> wrote:

 It looks like a load error is happening. Default loader is unsafe and then it points me to a web address for full details.
python3 ./tvscrobbler.py 
./tvscrobbler.py:21: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  config = yaml.load(open('data/config.yml', 'r'))

ready!

    On Thursday, May 21, 2020, 05:33:54 PM EDT, Todd Rock <wolverine30008@yahoo.com> wrote:  
 
  Yes. I have confirmed the date and time are correct.
    On Wednesday, May 20, 2020, 10:52:57 PM EDT, Vyacheslav Karpukhin <notifications@github.com> wrote:  
 
 


Are the date/time settings correct on that mac?

**Comment by stigger** [comment]
No, sorry, I can't solve the SSLCertVerificationError. Probably some kind of a local environment problem.

Also, I just noticed that you have hijacked another unrelated issue. Please create your own issues, and comment on existing only if you are sure that it's the same problem.

**Comment by wolverine30008** [comment]
Understood.  The issue above has resolved itself.  I have created a separate issue.

**Comment by intrepidsilence** [comment]
I have 4 devices. Is this (original) issue still being worked? If I cannot choose how will it determine which AppleTV is being used?

**Comment by stigger** [comment]
I haven't been working on this, but PRs are always welcome. I believe it will just pick the first Apple TV it gets from zeroconf. As a workaround, it should be easy enough to adjust the sources to filter them by name.

**Comment by stigger** [comment]
From now on it's possible to pick a specific Apple TV using config.yml:
```
apple_tv_identifier: 12:34:56:78:90:ab
```

**Comment by TheBlackBush** [comment]
> From now on it's possible to pick a specific Apple TV using config.yml:
> 
> ```
> apple_tv_identifier: 12:34:56:78:90:ab
> ```

Great!
I'm gald that you decided to move to pyatv... I'll test it today and let you know for any issue.
Can it run simultaneously with multiple ATVs or i need to config a specific ATV for every run?

**Comment by stigger** [comment]
> I'm gald that you decided to move to pyatv...

I wonder why. It's used only for the low-level communication with Apple TV, and just makes it easier to support tvOS 15. For versions prior to tvOS 15 there is no difference at all.

The possibility to pick a specific Apple TV is not related to the pyatv switch.

> Can it run simultaneously with multiple ATVs or i need to config a specific ATV for every run?

No, that's not supported, you'll need to run multiple instances for that, each one configured to work with a different Apple TV.
