### ISSUE TITLE
no connect to apple tv

### ISSUE THREAD

**Issue by sgremm** [stigger/trakt-for-appletv#4]
Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.create_connection() done, defined at /usr/lib/python3.7/asyncio/base_events.py:863> exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 910, in create_connection
    type=socket.SOCK_STREAM, proto=proto, flags=flags, loop=self)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1279, in _ensure_resolved
    proto=proto, flags=flags)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 789, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by stigger** [comment]
What does `dns-sd -B _mediaremotetv._tcp local` show?
