### ISSUE TITLE
Error running on mac

### ISSUE THREAD

**Issue by CelticWebSolutions** [stigger/trakt-for-appletv#9]
Ran code on my Mac, it asked for Trakt code, which I gave, it then gave the following errors

`Traceback (most recent call last):
  File "./tvscrobbler.py", line 49, in <module>
    launch(ScrobblingRemoteProtocol(load_config()))
  File "/Users/Celtic/Downloads/trakt-for-appletv-master/scrobbling.py", line 39, in __init__
    self.authenticate_trakt()
  File "/Users/Celtic/Downloads/trakt-for-appletv-master/scrobbling.py", line 49, in authenticate_trakt
    Trakt.configuration.defaults.oauth.from_response(response, refresh=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trakt/core/configuration.py", line 157, in from_response
    raise ValueError('Invalid "response" parameter provided to oauth.from_response()')
ValueError: Invalid "response" parameter provided to oauth.from_response()
`

Any idea why this would be?  I have tested to se start the Mac can see the Apple TV on the network and it can.

**Comment by stigger** [comment]
Please delete the file `data/trakt.auth` and try again. If it doesn't work on the first run after deleting the file, please let me know the details of the problem.
